### ISSUE TITLE
Which codebase and version of DKAN will we be using for Sierra Leone's site?

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/sldata#1]
Need to start uploading content, please let me know. 

Andrew suggested using a clone of the HHS demo site -- which would be awesome, but Federica and I are concerned about having to use Panelizer and would prefer to avoid it if possible.

@acouch @grantdobbe

**Comment by grantdobbe** [comment]
Right now, we're based on the HHS demo version of DKAN. I would like to see
us using dkan-drops or the nucivic-data version of DKAN in order to
facilitate easy updates.

Grant Dobbe
http://grant.dobbe.us
+1-608-469-9907

**Comment by janette** [comment]
The current SL build is behind a few commits and some of the problems that Stefanie is seeing have already been fixed in later releases.

**Comment by grantdobbe** [comment]
After a long discussion this afternoon, we're going to use data_starter_docroot as the new base repo. That ensures that new builds of DKAN will appear for SL and all NuCivic Data sites.

**Comment by jvitello** [comment]
Grant said the site is up-to-date, and his last comment seems to confirm an ongoing strategy. I'm closing this ticket.
