### ISSUE TITLE
Group icons are huge, text below icons is too big, hero image lacks colorizer shading

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/sldata#10]
![screen shot 2015-03-24 at 10 42 29 am](https://cloud.githubusercontent.com/assets/9059428/6804404/ccd643b6-d213-11e4-8a8b-afc7a232f0ee.png)

**Comment by topicus** [comment]
Done. 
![screen shot 2015-03-27 at 6 59 18 pm](https://cloud.githubusercontent.com/assets/381224/6877803/766f312a-d4b3-11e4-9194-c2b42adbc9c5.png)
![Uploading Screen Shot 2015-03-27 at 6.59.27 PM.png . . .]()

**Comment by stefaniefgray** [comment]
ARGENTINA = THE GREATEST. 
FUTURE 2018 WORLD CUP CHAMPIONS!

(Thank you, Mariano and Teo!)
