### ISSUE TITLE
Can't embed basic Recline map in blog entry

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/sldata#11]
Here's the blog entry: http://live.data.sierraleone.nucivic.build/story/airports-sierra-leone

This is the map that should be embedded: http://live.data.sierraleone.nucivic.build/dataset/airport-locations/resource/6bdcee60-e521-429c-9937-fe7bec478c1e#{currentView:!map,view-map:{lonField:!longitude_deg,latField:!latitude_deg},map:{bounds:{_southWest:{lat:7.226249208399038,lng:-14.666748046875},_northEast:{lat:9.941798345389335,lng:-9.667968749999998}}}}

I pasted the exact embed code from the map to the blog entry, and nothing is showing up at all.

**Comment by grantdobbe** [comment]
Issue is with the <iframe> tag being filtered.

**Comment by grantdobbe** [comment]
Fixed by adding <iframe> to the list of acceptable tags. http://live.data.sierraleone.nucivic.build/story/airports-sierra-leone

**Comment by drkloc** [comment]
I'm seeing the map at that url, i'm guessing the issues is that we need to hide the **upload field** and the **embed button**

**Comment by stefaniefgray** [comment]
Agreed!

**Comment by jvitello** [comment]
![blog_map](https://cloud.githubusercontent.com/assets/5174815/6856325/b8226dfa-d3d5-11e4-8a0c-1cb44954d2aa.png)

To clarify, the items in the red box should not be displayed.

**Comment by drkloc** [comment]
on this.

**Comment by drkloc** [comment]
![screen shot 2015-03-27 at 3 39 46 pm](https://cloud.githubusercontent.com/assets/428070/6874650/af65adf4-d497-11e4-899f-d70680d29cd7.png)

working as expected. Please review and close.

**Comment by stefaniefgray** [comment]
Looks perfect! Thank you @drkloc :)
