### ISSUE TITLE
cannot create new environments; cannot fully delete old ones

### ISSUE THREAD

**Issue by grantdobbe** [NuCivic/sldata#12]
I have been trying to create testing environments all night. No dice.

Backed up the site, deleted the project, started fresh, was able to create live and dev. Cannot create new environments beyond that.

When I try to delete unused environments, they remain in the listing.

![screenshot - 03242015 - 10 29 31 pm](https://cloud.githubusercontent.com/assets/2234943/6817909/47c91b5a-d275-11e4-874e-12bdf892e635.png)

I am going to go drink until this problem goes away, as we now have blockers upon blockers.

**Comment by Krista-Nuams** [comment]
this is lower in the triage than other previously allocated hours and can wait 24 hours due to a number of circumstances. Thank you for flagging this Grant. Let's regroup on Thursday.

**Comment by jonpugh** [comment]
Steps to fix

1. Log in via SSH: aegir@sierraleone.nucivic.build.
2. Try to verify a site:  `drush @hostmaster provision-verify`. Any provision-verify call tries to reload apache.
3. Noted an error message:

  ```
  <em>apache</em> on <em>sierraleone.nucivic.build</em> could not be restarted. Changes might  [warning]
  not be available until this has been done. (error: <em>apache2: Syntax error on line 234 of
  /etc/apache2/apache2.conf: Syntax error on line 25 of   /etc/apache2/conf.d/aegir.conf: Syntax
  error on line 16 of /var/aegir/config/server_master/apache/platform.d/platform_data_staging.conf: Could not open
configuration file /var/aegir/projects/data/staging/.htaccess: No such file or directory
Action &#039;graceful&#039; failed.
The Apache error log may have more information.</em>)
  ```
4. Looked at the project folder: `/var/aegir/projects/data`.  Each environment should have a folder here.
5. Discovered a second "project" node that shouldn't be there...  http://sierraleone.nucivic.build/node/597
6. Discovered many extra "platform" nodes that shouldn't be there:
  - 5 named sierraleone_live
  - 2 named sierraleone_dev
  - 1 named sierraleone_staging
  - Old "ebola" platforms.  
  - sldata_live, sl_data_dev3.
7. Attempting to delete the extra platforms and project...

**Comment by jonpugh** [comment]
Most of the old platforms have been "deleted", the nodes stay behind with aegir.

The main problem is there are actually 4 projects called "sierraleone".  Not sure why.

**Comment by jonpugh** [comment]
There is also a project called "platform"??

**Comment by jonpugh** [comment]
The "staging" environment record for the data project had a site NID for a node that didn't exist.

I updated the site column to 0, and re-verified data_staging platform which will clone the site codebase again...

**Comment by jonpugh** [comment]
Removed bad apache configs and unused drush aliases.

Had to fix the "test" environment record as well, and verified the platform, which unstuck that process so we now have:

 http://staging.data.sierraleone.nucivic.build/
http://kirkland.data.sierraleone.nucivic.build/
http://prep.data.sierraleone.nucivic.build/
http://dev.data.sierraleone.nucivic.build/
http://test.data.sierraleone.nucivic.build/

**Comment by jonpugh** [comment]
I am chalking this up to the fact that this server was originally setup for eboladata, and I manually renamed it and set it up for use by sierra leone instead.  

Something must have went wrong during that process.   I don't think it will happen again on up to date devshop servers because of this.

I've cloned live again to make sure that works.

**Comment by jonpugh** [comment]
Cloning worked fine.  Now for deleting...

**Comment by jonpugh** [comment]
Platform deletion failed due to the error 

'Existing sites were found on this platform. These sites will need to be deleted before this platform can be deleted.'

This means there is something in the ./sites folder, which i found is true: `./sites/hhs-demo.local/` somehow made it into the repo.

I've removed this and will try deleting again.

**Comment by jonpugh** [comment]
deletion worked.  Sites are up.  Grant is working on syncing files.
