### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by jvitello** [NuCivic/sldata#15]
The about page needs to be more meaningful to the site. Stefanie, I think you had an idea of what you were going to change it to. Would you update this ticket with your plan? We will probably deal with this tomorrow.

**Comment by jvitello** [comment]
This will be paraphrased from here:
http://dkan.nuamsdev.com/en/about

**Comment by stefaniefgray** [comment]
About page is posted: http://live.data.sierraleone.nucivic.build/about

Let me know what you think

**Comment by jvitello** [comment]
Andrew thinks the about page should just be removed for the time being. Put this as a low priority incase the world bank does deliver some copy later on.

**Comment by jvitello** [comment]
Ok, no word still from the World Bank. We should just take down the About page.

**Comment by stefaniefgray** [comment]
Just unpublished it - the copy I'd written is saved and the page can be published again when we're ready

**Comment by jvitello** [comment]
Great. Confirmed that it's gone, closing ticket.
