### ISSUE TITLE
Markup isn't formatting properly

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/sldata#2]
I copied and pasted the body of the 'How to Publish Data' page for EbolaData.org into the 'How to Publish Data' page for the Sierra Leone site, but none of the markup is working. 

They're both set as HTML, and it's pretty basic Drupal markup, such as double-asterisks for bold text.

EbolaData.org page: http://www.eboladata.org/how-publish-data
Sierra Leone page: http://live.data.sierraleone.nucivic.build/how-publish-data

**Comment by grantdobbe** [comment]
You're using Markdown for those pages. The filter is set to HTML, which isn't Markdown. Let me see if we have Markdown support in DKAN.

**Comment by grantdobbe** [comment]
Actually, it looks like the HTML filter includes Markdown support, which is slightly confusing. I might post an upstream ticket for this. 

In the meantime, I'll see what I can do for you. Markdown can be finicky sometimes.

**Comment by grantdobbe** [comment]
Ok, it looks like your section headings were formatted improperly.

```##section heading##``` is actually improper markup.

To get this:
## Section Heading

you need to do this:

```## section heading ```

**Comment by grantdobbe** [comment]
That's interesting. Most Markdown is working except for bold and italic. The formatting is correct (I checked it in a different markdown editor), but the site doesn't want to play ball.

**Comment by janette** [comment]
@grantdobbe check the text format, those tags might not be on the 'allowed' list

**Comment by grantdobbe** [comment]
@janette still happens even when I disable "limit allowed HTML tags"

**Comment by grantdobbe** [comment]
This appears to be resolved on production. Is that true?
