### ISSUE TITLE
Grant's on-site travel details

### ISSUE THREAD

**Issue by jvitello** [NuCivic/sldata#24]
Andrew is working out the details on whether the World Bank can cover all of the costs. Things look promising.

Need to start the process on the WB organizing the trip. Need to get Grant a UIP number. WB will provide details of the information they need shortly.

**Comment by jvitello** [comment]
Grant, would you send Qiyang this info?:

---------------

Follow Rob's email, I would be happy to request an UPI number for Grant and later arrange the trip for him with our team. Universal Personnel Identifier is needed for everyone work or travel for the Bank. It would be great if Grant could please provide answers to the three questions and items listed below at his earliest convenience

Questions:
1. Worked for the Bank Group in the past (as a staff member, or consultant, or as a contractor from a firm)?
2. Travelled on Bank Group Business in the past?
3. Is/Was the spouse or dependent of a Bank Group staff member?

Items:
1. scanned bio-page of the passport, 
2. social security number (if any) and 
3. preferred travel dates for the trip tentatively scheduled for the week of May 17th.

We can move the logistic aside to a separate email but please do let me know shall you have any questions. I will forward the invite to VC with OGI Sierra Leone at 11am-1pm tomorrow. Thanks.

Best, 

___________________________________
Qiyang Xu
Leadership, Learning and Innovation
T +1 (202) 473-7383 
E qxu1@worldbank.org
W www.worldbank.org
J3-286C. 1818 H Street, N.W. Washington, D.C. 20433

**Comment by jvitello** [comment]
@grantdobbe Did you send a copy of your passport to Qiyang? Were you able to get in touch via phone for your SSN?

**Comment by grantdobbe** [comment]
Everything's now taken care of. They're booking my flight.
