### ISSUE TITLE
Views security bug fix

### ISSUE THREAD

**Issue by jvitello** [NuCivic/sldata#27]
There is a security bug with Views that is currently being addressed by an update to the Views module in DKAN.

https://github.com/NuCivic/dkan/pull/453

Once this is complete and tested, the Softlayer sites can be updated.

**Comment by jvitello** [comment]
Dan, assigning this ticket to you since you are the Mars scrum master and Sierra Leone will be your team's responsibility. This shouldn't be Neptune's responsibility until the site is launched and passed over for general support. Let me know if you think otherwise.

**Comment by jpasila** [comment]
reassigning to @grantdobbe for follow up / close out

**Comment by jonpugh** [comment]
Closing, will take care of in NuCivic/mynucivic/issues/78
