### ISSUE TITLE
Recline can't handle percentages in charts

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/sldata#3]
Attempted to make a chart from a dataset about voter turnout that had percentages:

![screen shot 2015-03-20 at 1 23 23 pm](https://cloud.githubusercontent.com/assets/9059428/6757034/566d5c58-cf04-11e4-9a87-0274ef9f20a3.png)

(See the second column for voter turnout by year)

![screen shot 2015-03-20 at 1 24 06 pm](https://cloud.githubusercontent.com/assets/9059428/6757079/a7c94666-cf04-11e4-9e25-63d7608311c5.png)

In the above screenshot, Recline seems to have completely misinterpreted what the numbers are.

![screen shot 2015-03-20 at 1 24 31 pm](https://cloud.githubusercontent.com/assets/9059428/6757180/852795b2-cf05-11e4-92e9-1e4304f6ad0b.png)

But as shown in this screenshot, Recline is able to graph the data when it's in pure integers (voter registration counts).

**Comment by grantdobbe** [comment]
@drkloc could you give me a hand here?

**Comment by drkloc** [comment]
@topicus will start on this. I'll finish #5 first and then help him on this.

**Comment by topicus** [comment]
On this.

**Comment by drkloc** [comment]
http://live.data.sierraleone.nucivic.build/dataset/voter-turnout-data-sierra-leone/resource/0f40bcc6-0b88-45aa-a0b2-c85813ca9759#{view-graph:{group:!Year,series:[!Voter++Turnout],graphOptions:{hooks:{processOffset:{},bindEvents:{}}}},currentView:!graph,graphOptions:{hooks:{processOffset:{},bindEvents:{}}}}
