### ISSUE TITLE
Choropleth module isn't working

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/sldata#5]
http://live.data.sierraleone.nucivic.build/visualization/choropleth_visualization/10

^^ No map is showing at all. It was working fine on the old server.

I double checked the geoJSON file associated with the map, and it's loading properly on its own: http://live.data.sierraleone.nucivic.build/geo_file/geojson/5

The CSV data associated with this map is also formatted properly: http://live.data.sierraleone.nucivic.build/dataset/evd-cases-district/resource/7f468728-27f6-4989-92fd-c8275c44106f#{view-graph:{graphOptions:{hooks:{processOffset:{},bindEvents:{}}}},graphOptions:{hooks:{processOffset:{},bindEvents:{}}}}

**Comment by stefaniefgray** [comment]
Update: Just tested it again, and it's still not working.

**Comment by drkloc** [comment]
on this.

**Comment by drkloc** [comment]
this is working now. Sorry for the delay.

http://live.data.sierraleone.nucivic.build/visualization/choropleth_visualization/1
