### ISSUE TITLE
Upload dataset elements are loading misaligned

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/sldata#8]
![screen shot 2015-03-23 at 9 14 44 pm](https://cloud.githubusercontent.com/assets/9059428/6793932/03cd7302-d1a2-11e4-85de-6e188666813e.png)

^^  The secondary URL box is floating to the right of the first one

![screen shot 2015-03-23 at 9 15 13 pm](https://cloud.githubusercontent.com/assets/9059428/6793934/09971bd0-d1a2-11e4-842f-dcdeea012562.png)

^^  The longer the title, the more the URL box gets pushed to the right

**Comment by grantdobbe** [comment]
Do you have an example URL? Also, please see if this is happening on http://dev2.data.sierraleone.nucivic.build/
