### ISSUE TITLE
Errors when uploading new datasets/resources

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/sldata#9]
![screen shot 2015-03-23 at 11 42 15 pm](https://cloud.githubusercontent.com/assets/9059428/6795450/444cfcc2-d1b6-11e4-9bbf-3326fcb26e3b.png)

^ I keep getting this message over and over, even if I go back to square one and manually re-enter everything. I'm just trying to create a dataset for the World Bank's climate change data, nothing out-of-the-ordinary. The URL doesn't lead to anything, and no new nodes are being created.

This is a definite blocker, can't figure out why it's happening. No bueno.

**Comment by grantdobbe** [comment]
please test this on http://dev2.data.sierraleone.nucivic.build/ and let me know if you can upload a dataset.

**Comment by stefaniefgray** [comment]
Can now upload datasets, whew.
